# Local configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost/moneymanagement?useSSL=false&allowPublicKeyRetrieval=true
    username: postgres
    password: changeme
    driver-class-name: org.postgresql.Driver
